+ финальное задание спринта 8 версия 1
Triapkin/java-kanban pull request #1
Opened 2024-04-18 10:51 UTC by Triapkin

финальное задание спринт 8 версия 1

2024-04-20 14:21 UTC, dgumich requested changes

2024-04-20 14:21 UTC, dgumich commented on src/test/managers/TaskManagerTest.java
> +import org.junit.jupiter.api.DisplayName;
Добавь тестовую библиотеку в проект, что бы проверяющему не приходилось ее скачивать самому=)

2024-04-20 14:21 UTC, dgumich commented on src/test/managers/FileBackedTasksManagerTest.java
> +    File file;
В тестах все так же как и в обычном коде: поля должны быть приватными)

2024-04-20 14:21 UTC, dgumich commented on src/test/managers/FileBackedTasksManagerTest.java
> +        file = CsvUtils.createIfFileNotExist();
Почему-то не работает=(
![image](https://github.com/Triapkin/java-kanban/assets/42573998/595ead92-aecd-4a87-975b-f1a9922ad9bc)

2024-04-20 14:21 UTC, dgumich commented on src/test/tasks/EpicTests.java
> +    TaskManager manager;
Аналогично, поле должны быть приватным

2024-04-20 14:21 UTC, dgumich commented on src/test/tasks/EpicTests.java
> +    public void epicStatusEqualNewThenAllSubtaskStatusIsNew() {
Не работает=(
![image](https://github.com/Triapkin/java-kanban/assets/42573998/917f28ec-5693-4f2d-8003-2ef965bf0407)

2024-04-22 17:12 UTC, dgumich requested changes

2024-04-22 17:12 UTC, dgumich commented on src/test/managers/InMemoryHistoryManagerTest.java
> +        Task task1 = new Task(1, "Task", "task_description", Status.NEW, TaskType.TASK, 60, LocalDateTime.now());
Так же как и в обычном коде, общую часть надо выносить в методы. Здесь, например, мы несколько раз создаем три задачи и добавляем их в менеджер. Как раз это можно и вынести в отдельный метод.

2024-04-22 17:12 UTC, dgumich commented on src/test/managers/InMemoryHistoryManagerTest.java
> +    public void addTasksToHistory() {
Название тестов строится по правилу: слово test (думаю, понятно зачем=)), оно может быть в начале или в конце, потом название метода, который тестируется и условия. Получается очень длинное название, зато точно описывает, что проверяем. Зачем такое? Дело в том, что юнит тесты запускаются постоянно при сборке. И вот ты написал новый код, а какой-то тест упал. Это значит, что или поменялось поведение и надо понять почему и пофиксить или надо обновить тестовые данные. Вот длинное название тебе как раз поможет разобраться что это за тест и что проверяет.
Поэтому правильное название было бы:
testAddShouldSuccefullyAddTasksToHistory
Здесь можешь почитать про название тестов:
https://www.baeldung.com/java-unit-testing-best-practices

2024-04-22 17:12 UTC, dgumich commented on src/implementation/InMemoryTaskManager.java
> +        return prioritizedTasks;
Возвращать ссылку на исходный объект - плохая практика. Такое уже было со список истории просмотров: вы возвращали копию листа. Здесь так же надо возвращать копию, а не оригинальный сет.

2024-04-22 17:30 UTC, Triapkin commented on src/test/managers/FileBackedTasksManagerTest.java
> +    File file;
исправил

2024-04-22 17:30 UTC, Triapkin commented on src/test/managers/FileBackedTasksManagerTest.java
> +        file = CsvUtils.createIfFileNotExist();
починил)

2024-04-22 17:30 UTC, Triapkin commented on src/test/tasks/EpicTests.java
> +    TaskManager manager;
исправил

2024-04-22 17:31 UTC, Triapkin commented on src/test/tasks/EpicTests.java
> +    public void epicStatusEqualNewThenAllSubtaskStatusIsNew() {
починил

2024-04-23 06:58 UTC, merged