+ финальное задание спринта 9 версия 1
Triapkin/java-kanban pull request #2
Opened 2024-05-01 12:09 UTC by Triapkin

2024-05-02 02:19 UTC, dgumich requested changes

2024-05-02 02:19 UTC, dgumich commented on src/http/HttpTaskServer.java
> +import com.google.gson.Gson;
Добавь библиотеку GSON в папку lib вместе к Junit джарникам

2024-05-02 02:19 UTC, dgumich commented on src/test/http/HttpTaskServerTests.java
> +    public void setUpBeforeClass() throws Exception {
Метод не выбрасывает исключений, так что нужно убрать это.

2024-05-02 02:19 UTC, dgumich commented on src/test/http/HttpTaskServerTests.java
> +    TaskManager manager = new InMemoryTaskManager();
Поля в тестах должны быть приватными

2024-05-02 02:19 UTC, dgumich commented on src/http/HttpTaskServer.java
> +    public static void initialization() throws IOException {
Зачем методы/поля сделал статичными? Мы запускаем сервер, то есть какой-то объект. Статичные методы используют только для утильных классов (и то, некоторые предпочитают обычные методы даже там).
Статику очень использовать в тесте (мокать). Да и здесь нет в ней смысла.

2024-05-02 05:16 UTC, Triapkin commented on src/test/http/HttpTaskServerTests.java
> +    public void setUpBeforeClass() throws Exception {
исправил

2024-05-02 05:16 UTC, Triapkin commented on src/test/http/HttpTaskServerTests.java
> +    TaskManager manager = new InMemoryTaskManager();
исправил

2024-05-02 05:16 UTC, Triapkin commented on src/http/HttpTaskServer.java
> +import com.google.gson.Gson;
исправил

2024-05-02 05:24 UTC, Triapkin commented on src/http/HttpTaskServer.java
> +    public static void initialization() throws IOException {
исправил

2024-05-03 00:52 UTC, dgumich requested changes

2024-05-03 00:52 UTC, dgumich commented on src/test/http/HttpTaskServerTests.java
> +    TaskManager manager = new InMemoryTaskManager();
А это поле почему не приватное?=)

2024-05-03 00:52 UTC, dgumich commented on src/test/http/handlers/EpicHandlerTests.java
> +    TaskManager manager = new InMemoryTaskManager();
Аналогично и здесь, поля должны быть приватными

2024-05-03 00:52 UTC, dgumich commented on src/test/http/handlers/EpicHandlerTests.java
> +    public EpicHandlerTests() throws IOException {
Зачем нужен этот конструктор?

2024-05-03 00:52 UTC, dgumich commented on src/test/http/handlers/HistoryAndPrioritizedTests.java
> +    HttpTaskServer server = new HttpTaskServer(manager);
Поля так же должны быть приватными

2024-05-03 00:52 UTC, dgumich commented on src/test/http/handlers/TaskHandlerTests.java
> +    TaskManager manager = new InMemoryTaskManager();
И тут поля должны быть приватными

2024-05-03 00:52 UTC, dgumich commented on src/test/http/handlers/EpicHandlerTests.java
> +    public void getEpicById() throws IOException, InterruptedException {
Название тестовых методов не совсем соответствуют правилам, но это не критично
https://www.baeldung.com/java-unit-testing-best-practices

2024-05-03 07:37 UTC, merged